project:
  type: website

website:
  title: "Edmund Kelly"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Research.qmd
        text: Research

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

