project:
  type: website

website:
  title: "Edmund Kelly"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: Publications.qmd
        text: Publications
      - href: Working papers.qmd
        text: Working papers
      - href: teaching.qmd
        text: Teaching

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

